name: movie_booking_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 #cupertino icon pack
  auto_route: ^7.8.3 #router
  video_player: ^2.8.2 #video player plugin
  dio: ^5.4.0 #http client
  freezed_annotation: ^2.4.1 #model parsing annotator
  flutter_staggered_grid_view: ^0.7.0 #used to display
  barcode_widget: ^2.0.4 #used in ticket screen
  get_it: ^7.6.7 #used for dependency injection
  flutter_bloc: ^8.1.3 #state-management
  intl: ^0.19.0 #date-time conversion
  youtube_player_flutter: ^8.1.2
  hive: ^2.2.3
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2 #model generator
  json_serializable: ^6.7.1 #model generator
  auto_route_generator: ^7.3.1 #route generator

flutter:
  uses-material-design: true
  assets:
    - .env #add this with your own API_KEY

scripts: #shortcut build scripts
  build: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch
